language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jeffcrouse/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jeffcrouse/docker-react npm run test